# Generated by Django 4.1.7 on 2023-03-15 11:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('order_side', models.CharField(max_length=255, null=True)),
                ('order_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('average_order_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_type', models.CharField(max_length=255, null=True)),
                ('order_status', models.CharField(max_length=255, null=True)),
                ('order_total_executed_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_total_executed_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_total_executed_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('provider', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'crypto_tradeordertransaction',
            },
        ),
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='position_side',
        ),
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='provider',
        ),
        migrations.AddField(
            model_name='tradepnltransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnl_transaction', to='crypto.tradeorder'),
        ),
    ]
