# Generated by Django 4.1.7 on 2023-03-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_tradeorder_remove_tradepnltransaction_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepnltransaction',
            name='instrument_name',
        ),
    ]
