# Generated by Django 4.1.7 on 2023-03-17 18:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_remove_tradepnltransaction_position_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'crypto_accountinvestor',
            },
        ),
        migrations.CreateModel(
            name='PortfolioWalletBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=21, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'crypto_portfoliowalletbalance',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.PositiveSmallIntegerField()),
                ('transaction_currency', models.CharField(max_length=255)),
                ('chain_currency', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('txid', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=21, null=True)),
                ('created_at', models.DateTimeField()),
                ('note', models.CharField(max_length=255)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transfer', to='crypto.accountprofile')),
            ],
            options={
                'db_table': 'crypto_portfoliotransfer',
            },
        ),
    ]
