# Generated by Django 4.1.7 on 2023-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_accountprofile_portfoliowalletbalancesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliowalletbalancesnapshot',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=21),
        ),
    ]
