# Generated by Django 4.1.7 on 2023-03-17 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_alter_portfoliowalletbalancesnapshot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliowalletbalancesnapshot',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21),
        ),
    ]
