# Generated by Django 4.1.7 on 2023-03-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_rename_address_portfoliotransfer_from_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliowalletbalancesnapshot',
            old_name='type',
            new_name='portfolio_type',
        ),
        migrations.CreateModel(
            name='PortfolioAccountInvestmentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_percentage', models.DecimalField(decimal_places=8, max_digits=21)),
                ('portfolio_id', models.SmallIntegerField(default=1, null=True)),
                ('portfolio_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_investment_user', to='crypto.portfolioaccountprofile')),
            ],
            options={
                'db_table': 'crypto_portfolioaccountinvestmentparticipation',
            },
        ),
    ]
