# Generated by Django 4.1.7 on 2023-03-28 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_rename_type_portfoliowalletbalancesnapshot_portfolio_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='order_quantity_test',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21),
        ),
    ]
