# Generated by Django 4.1.7 on 2023-03-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_tradeorder_order_quantity_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='order_quantity_test',
        ),
    ]
