version: "3"

services:
  app:
    image: misko:latest
    build:
      context: .
    restart: always
    env_file:
      - ./.env.app
    ports:
      - 8000:8000

  db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.db
      ports:
        - 54321:5432


volumes:
  postgres_data:
