# Generated by Django 4.1.7 on 2023-03-13 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradePnLTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('position_side', models.CharField(max_length=255)),
                ('position_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('order_type', models.CharField(max_length=255)),
                ('position_closed_size', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('total_entry_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('average_entry_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('total_exit_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('average_exit_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('closed_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=21)),
                ('created_at', models.DateTimeField()),
                ('provider', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'crypto_tradepnltransaction',
            },
        ),
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('provider', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'crypto_marketinstrument',
                'unique_together': {('name', 'provider')},
            },
        ),
    ]
