# Generated by Django 4.1.7 on 2023-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('provider', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'crypto_marketinstrument',
                'unique_together': {('name', 'provider')},
            },
        ),
    ]
