# Generated by Django 4.1.7 on 2023-03-19 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_rename_accountprofile_portfolioaccountprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliotransfer',
            old_name='address',
            new_name='from_recipient',
        ),
        migrations.RemoveField(
            model_name='portfolioaccountprofile',
            name='provider',
        ),
        migrations.AddField(
            model_name='portfoliotransfer',
            name='network_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliotransfer',
            name='portfolio_type',
            field=models.CharField(default='DERIVATIVE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliotransfer',
            name='to_recipient',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliotransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliotransfer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliotransfer',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
