# Generated by Django 4.1.7 on 2023-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_rename_type_portfoliowalletbalancesnapshot_portfolio_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorder',
            name='order_side',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TradePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=255)),
                ('unrealised_pnl', models.DecimalField(decimal_places=8, max_digits=21)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'crypto_tradeposition',
                'unique_together': {('instrument_name', 'unrealised_pnl', 'provider')},
            },
        ),
    ]
