# Generated by Django 4.1.7 on 2023-04-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_tradeorder_order_side_tradeposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorder',
            name='order_side',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
