# Generated by Django 4.1.7 on 2023-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('referrer_uuid', models.CharField(max_length=255, unique=True)),
                ('status', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'account_profile',
            },
        ),
        migrations.DeleteModel(
            name='AccountReferral',
        ),
    ]
