# Generated by Django 4.1.7 on 2023-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=21)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=21)),
                ('transfer_fee', models.DecimalField(decimal_places=8, max_digits=21, null=True)),
                ('network_fee', models.DecimalField(decimal_places=8, max_digits=21, null=True)),
                ('type', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField()),
                ('currency', models.PositiveSmallIntegerField()),
                ('datetime', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
