# Generated by Django 4.1.7 on 2023-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_accountwalletbalance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='selected_currency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
